font:
  size: 8
  # To get the list of available options, use:
  #   fc-list : family style
  normal:
    family: JetBrainsMono Nerd Font Mono
    style: Regular
  bold:
    family: JetBrainsMono Nerd Font Mono
    style: Bold
  italic:
    family: JetBrainsMono Nerd Font Mono
    style: Italic
key_bindings:
# Change this to CreateNewWindow once Alacritty gets updated
- { key: N, mods: Control, action: SpawnNewInstance }
- { key: V, mods: Control, action: ToggleViMode }
